<a href="https://colab.research.google.com/github/RicheTasnim/pythonForML/blob/main/module_11.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

arr = np.random.randint(1, 100, size =(10,5)) #sample 10, feature 5

In [ ]:
arr.shape

(10, 5)

In [ ]:
b = arr.reshape(5,10)

b.shape
b.ndim
b

array([[13, 46,  7, 61, 63, 81, 61,  4, 10, 21],
       [91, 40, 40, 49, 45, 19, 77,  9, 69, 74],
       [74, 42, 73, 75,  5, 70, 73, 83, 86, 83],
       [29,  7, 15,  4, 10, 72, 37, 22, 25, 44],
       [34, 46, 20, 40, 48, 72, 72, 85, 73, 28]])

In [ ]:
flatten = b.flatten()
print(flatten.ndim)
flatten

column_wise_flattening = np.ravel(b, order = 'C')

print(column_wise_flattening)

1
[13 46  7 61 63 81 61  4 10 21 91 40 40 49 45 19 77  9 69 74 74 42 73 75
  5 70 73 83 86 83 29  7 15  4 10 72 37 22 25 44 34 46 20 40 48 72 72 85
 73 28]


In [ ]:
a = np.random.randint(1,10, size =(2,3))
b = np.random.randint(20,30, size =(2,3))

print(a)
print(b)

[[2 7 1]
 [7 7 2]]
[[28 26 29]
 [27 25 23]]


In [ ]:
# Concatenate

con_row = np.concatenate((a,b), axis=0) #row wise
print(con_row)

con_col = np.concatenate((a,b), axis = 1) #column wise
print(con_col)

[[ 2  7  1]
 [ 7  7  2]
 [28 26 29]
 [27 25 23]]
[[ 2  7  1 28 26 29]
 [ 7  7  2 27 25 23]]


In [ ]:
# error

#row wise concatenate korar somoy column same thakbe
#col wise concatenate koror somoy row ta same thakte hobe

x = np.random.randint(1, 10, size = (2,3))
y = np.random.randint(1, 10, size = (1,3))

r = np.concatenate((x,y), axis = 0)
r = np.concatenate((x,y), axis = 1)

print(r)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

In [ ]:
#transpose

mat = np.array([[10,20,30],
                [30,40,50]])
transpose = mat.T
print(transpose)

[[10 30]
 [20 40]
 [30 50]]


In [ ]:
# array split

a = np.random.randint(1, 10, size =(10,))
print(a)
splitted_array = np.array_split(a,3)

print(splitted_array)

#split -> equal division
splitted_array = np.split(a,3)

[1 8 1 3 3 8 3 9 1 8]
[array([1, 8, 1, 3]), array([3, 8, 3]), array([9, 1, 8])]


ValueError: array split does not result in an equal division

# arithmatic operator and mathematical functions

In [ ]:
# faster for vectorization

x = np.array([10, 8, 30, 100])
y = np.array([2, 3, 4, 5])

add = np.add(x,y)
print(add)

sub = x - y
print(sub)

mul = x * y
print(mul)

div = x/y
print(div)

reminder = x % y
print(reminder)

[ 12  11  34 105]
[ 8  5 26 95]
[ 20  24 120 500]
[ 5.          2.66666667  7.5        20.        ]
[0 2 2 0]


In [ ]:
#mathematical function
#trigonometry
#sin, cos, tan takes values in radian

sin_val = np.sin(x)
print(sin_val)

cos_val = np.cos(x)
print(cos_val)

deg_con = np.rad2deg(x)
print(deg_con)

rad_con = np.deg2rad(x)
print(rad_con)

[-0.54402111  0.98935825 -0.98803162 -0.50636564]
[-0.83907153 -0.14550003  0.15425145  0.86231887]
[ 572.95779513  458.3662361  1718.87338539 5729.57795131]
[0.17453293 0.13962634 0.52359878 1.74532925]


In [ ]:
#log

x = np.array([10, 8, 16, 100])
base_10_log_val = np.log10(x)
print(base_10_log_val)

two_diye_bhag = np.log2(x)
print(two_diye_bhag)

sqrt = np.sqrt(x)
print(sqrt)

[1.         0.90308999 1.20411998 2.        ]
[3.32192809 3.         4.         6.64385619]
[ 3.16227766  2.82842712  4.         10.        ]


In [ ]:
#different
s = np.sum(x)
print(s)

#prefix sum
cumul =np.cumulative_sum(x)
print(cumul)

134


AttributeError: module 'numpy' has no attribute 'cumulative_sum'

In [ ]:
# broadcasting

x = np.array([10, 8, 16, 100])

result = x + 2

#rulings = columns er size and vector er size same hote hobe

matrix = np.array([[10,20,30], [30,40,50]])

reult = matrix + 2

vector = np.array([1,2,3,4])

result = matrix + vector
print(result)

ValueError: operands could not be broadcast together with shapes (2,3) (4,) 

#Logical Function

In [ ]:
# comparison - >, <, >=, <=, ==, !=

x = np.array([10, 8, 16, 100])
y = np.array([2, 3, 16, 5])

greater_than = x>y
print(greater_than)

equal = x==y

print(equal)

#all () -> sob true kina
#any() -> jekuno ekta true ki na

print(np.all(greater_than))
print(np.any(equal))

[ True  True False  True]
[False False  True False]
False
True


#Sorting

In [ ]:
#inplace
x = np.array([10, 8, 16, 100])

z = x.copy()
print(z)

z.sort()
print(z)

[ 10   8  16 100]
[  8  10  16 100]


In [ ]:
#copy sorting
print(x)
sort_arr = np.sort(x)

print(sort_arr)
print(x)

[ 10   8  16 100]
[  8  10  16 100]
[ 10   8  16 100]


In [ ]:
# 2nd array sorting
mat = np.array([[10,3,5],[8,4,9]])

#horizon axis = 1

hor_sort = np.sort(mat, axis=1)
print(hor_sort)

vert_sort = np.sort(mat, axis=0)
print(vert_sort)

[[ 3  5 10]
 [ 4  8  9]]
[[ 8  3  5]
 [10  4  9]]


# Searching

In [ ]:
print(x)

[ 10   8  16 100]


In [ ]:
#np.where( condition, x, y) if true x, otherwise replace with y

index = np.where(x==8) #returns index
print(index)

arr = np.where(x>8,x,0)
print(arr)

(array([1]),)
[ 10   0  16 100]


In [ ]:
print(mat)

[[10  3  5]
 [ 8  4  9]]


In [ ]:
index = np.where(mat>8) #returns index
print(index)

arr = np.where(mat>8, mat, 0)
print(arr)

(array([0, 1]), array([0, 2]))
[[10  0  0]
 [ 0  0  9]]


In [ ]:
x = np.array([10, 100, 8, 16, 100])

maximum_vlaue_indx = np.argmax(x)
minimum_vlaue_indx = np.argmin(x)

print(maximum_vlaue_indx)
print(minimum_vlaue_indx)

1
2


# counting in ndarray

In [ ]:
a = np.random.randint(1, 100, size = (100,))
print(a)

[12 16  6 85 10 85 56 65 75 46  3 48 38 96 87 19 50 29 10  1 34 66 58 56
 70 14 86 57 22 64 13 72 49 15 75  3 90 35 39 40 16 86 57 19 63 22 48 67
 26 41 18 19 29  2 57 40  6 41 95 97 52 54  5 22 18  3 98 12 37 11 69 78
 98 94 38 82 29 21 45 85 29 35 81 73 89 84 51 24 58 80 34  7 98 90 68 51
 88 62 48 26]


In [ ]:
value_great_than_60 = np.count_nonzero(a==97)
print(value_great_than_60)

1


In [ ]:
unique_value, count = np.unique(a, return_counts=True)

print(unique_value)
print(count)

[ 1  2  3  5  6  7 10 11 12 13 14 15 16 18 19 21 22 24 26 29 34 35 37 38
 39 40 41 45 46 48 49 50 51 52 54 56 57 58 62 63 64 65 66 67 68 69 70 72
 73 75 78 80 81 82 84 85 86 87 88 89 90 94 95 96 97 98]
[1 1 3 1 2 1 2 1 2 1 1 1 2 2 3 1 3 1 2 4 2 2 1 2 1 2 2 1 1 3 1 1 2 1 1 2 3
 2 1 1 1 1 1 1 1 1 1 1 1 2 1 1 1 1 1 3 2 1 1 1 2 1 1 1 1 3]


#statistical function

In [ ]:
# data load

data = np.genfromtxt('student_scores.csv' ,delimiter=',',skip_header=1)

print(data)

FileNotFoundError: student_scores.csv not found.

In [ ]:
# statistics
math_marks = data[::,:1]

print(math_marks.T)

max_math_marks  = np.max(math_marks)
print(max_math_marks)

min_math_marks = np.min(math_marks)
print(min_math_marks)

average_math_marks = np.mean(math_marks)
print(average_math_marks)

median_math_marks = np.median(math_marks)
print(median_math_marks)

#standard deviation

std_math_marks = np.median(math_marks)
print(std_math_marks)

NameError: name 'data' is not defined

# Linear Algebra

In [ ]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

B = np.array([
    [7, 8],
    [9, 10],
    [11, 12]
])

# a er column and b er row same length hote hobe
dot_product = np.dot(A,B)
print(dot_product)

#trace
print(np.trace(B))

[[ 58  64]
 [139 154]]
17


In [ ]:
sq_mat = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]
                   ])

det_of_sq = np.linalg.det(sq_mat)
rank_sq = np.linalg.matrix_rank(sq_mat)

print(det_of_sq)
print(rank_sq)

0.0
2


In [ ]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print(np.dot(A,B))

[[19 22]
 [43 50]]
